# Generated by Django 3.2.4 on 2021-06-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('name', models.CharField(default=None, max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
