# Generated by Django 3.2.4 on 2021-06-20 14:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_identifier', models.CharField(default=uuid.uuid4, max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=1, default=0.0, max_digits=7)),
                ('product', models.ManyToManyField(to='product.Products')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
