# Generated by Django 3.2.4 on 2021-06-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.products')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='order_management.OrderedProduct'),
        ),
    ]
